baseURL: https://chengzhou1.netlify.app/
languageCode: en
DefaultContentLanguage: en
title: Website of Jane Doe
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
params:
  author: Chengzhou Wu
  customCss: []
  customJs: []
  description: Call me Chengzhou
  doNotLoadAnimations: no
  favicon: favicons/
  images: images/site-feature-image.png
  keywords: ''
  mainSections: post
  math:
    enable: no
    use: katex
  profilePicture: images/profile.jpg
  simpleAnalytics: {}
  socialIcons:
    - icon: fab fa-linkedin
      title: Linkedin
      url: https://www.linkedin.com/in/chengzhou-wu-81854713a/
    - icon: fab fa-github
      title: GitHub
      url: https://github.com/chengzhouwu
    - icon: fab fa-facebook
      title: facebook
      url: https://www.facebook.com/chengzhou.wu.9
    - icon: fas fa-envelope
      title: e-mail
      url: chengzhouwu8@gmail.com
  title: I'm Chengzhou
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 100
    - identifier: posts
      name: Posts
      url: /post/
      weight: 200
    - identifier: about
      name: About
      url: /about/
      weight: 300
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 400
